### PR TITLE
respectTestExecutionEnvironmentInPharo

### LINKED ISSUE #307: Running tests in Pharo6 should set up TestExecutionEnvironment
In Pharo6 TestExecutionEnvironment was introduced. It is possible process specific value of CurrentExecutionEnvironment.
Some libraries already use it. And travis failed to run their tests correctly

### PR DESCRIPTION
**Pull request by dionisiydk**
basicRunCase: is added to be able override it in platform subclasses.
Pharo test runner rans case by runCaseManaged
And Pharo version of #runAll rans testsuite in test environment

It fixes #307

### CODE REVIEW

**Comment by fniephaus** [comment]
@theseion @peteruhnak @Uko I never heard about the `TestExecutionEnvironment`, so can one of you comment on this?

**Comment by theseion** [comment]
Execution environments are a cool addition by @dionisiydk to Pharo. In the case of tests for example, the execution environment can keep track of processes forked from the test and can manage their termination.

I guess it should be straight forward to add a condition for this to the Pharo platform classes. I can take a look tonight.

**Comment by dionisiydk** [comment]
Hi @fniephaus. Read about it here [http://forum.world.st/SUnit-improvements-need-review-and-feedback-td4913413.html](http://forum.world.st/SUnit-improvements-need-review-and-feedback-td4913413.html).

Now I will try to fix pull request. I forgot that execution environment was introduced in Pharo 6. So some conditions are needed.

**Comment by dionisiydk** [comment]
Another question: can I use Iceberg to contribute? It produces metacello less format and I see that Gemstone log shows related errors.

**Comment by theseion** [comment]
@fniephaus will have to decide that but currently the repo uses normal filetree layout and we'd need to convert it first. I'm pretty sure that will lead to problems with Squeak and Gemstone though, so I don't think it's a good idea. At least not yet.

**Comment by dionisiydk** [comment]
I updated code with old pharo compatibility.
But I still used Iceberg so there is still problem with it.
Could you merge only code changes? Maybe it is simplest way to avoid repo format problem.

**Comment by theseion** [comment]
Merged your changes manually.

**Comment by fniephaus** [comment]
> Another question: can I use Iceberg to contribute? It produces metacello less format and I see that Gemstone log shows related errors.

@dionisiydk: please do not use metadata-less FileTree just yet. smalltalkCI provides compatibility to a wide range of different Smalltalk images, and not all of them support the new format yet. But it'd be great to use the new format soon in the future...

**Pull request closed without merging**
