### PR TITLE
Update Moose CI

### PR DESCRIPTION
**Pull request by badetitou**
Moose 32 8.0 doesn't exist
The url for Moose 8 does not follow the same format

### CODE REVIEW

**Comment by fniephaus** [comment]
Some of the Moose tests did not pass. Not sure why, could you please have a look?

**Comment by badetitou** [comment]
It looks like it's not moose the problem but Pharo 8.
The build of Pharo 8 is failing with the same error.

**Comment by fniephaus** [comment]
The Pharo alpha builds fail due to `unknown option: --nodisplay` ([see here](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/565512226#L472)). Could someone familiar with the Pharo VM (@estebanlm?) comment on this? Why has it been removed and is there a replacement?

**Comment by fniephaus** [comment]
@badetitou [This build](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/565512246#L667) failed due to a `download_file() expects an URL and a target path.` error. Could you please have a look at this?

**Comment by badetitou** [comment]
@fniephaus we have decided to remove the build 32bits for Moose 8.0.
I forgot to remove the entry in .travis.yml
It should be fixed

**Comment by badetitou** [comment]
It looks like it works when you ignore the coverage problem?

**Comment by fniephaus** [comment]
> it looks like it works when you ignore the coverage problem?

Yes, but that's another problem which should be fixed at some point.
Anyway, thanks for the contribution!

**Comment by fniephaus** [comment]
> it looks like it works when you ignore the coverage problem?

Yes, but that's another problem which should be fixed at some point.
Anyway, thanks for the contribution!

**Pull request merged**
