### PR TITLE
Add load config params #userEnv and #passwordEnv

### PR DESCRIPTION
**Pull request by LinqLover**
These new parameters make it possible to provide secret credentials via environment variables instead of hard-coding them into the configuration file. At the moment only supported by `SCIGoferLoadSpec` and `SCIMonticelloLoadSpec`, support will be added for `SCIMetacelloLoadSpec` after #485 has been merged.

This change was also requested in https://github.com/hpi-swa/smalltalkCI/pull/485#issuecomment-723511286.

Usage:
```ston
SCIMonticelloLoadSpec {
  #url : 'http://ss3.gemtalksystems.com/ss/...',
  #packages : ['MyProject-Core'],
  #versions : ['MyProject-Core-aa.12'],
  #usernameEnv : 'USERNAME_VAR',
  #passwordEnv : 'PASSWORD_VAR'
}
```

Open todos:
- [x] Write unit tests
- [x] Write acceptance tests?

  I did not find any existing acceptance tests for `.ston` configuration files (except for `.smalltalk_fail.ston`), so I don't think this should be necessary. @fniephaus What is your opinion? :-)
- [x] `SCIGoferLoadSpec` and `SCIMonticelloLoadSpec` (and, after #485, `SCIMetacelloLoadSpec`, too) share a certain amount of code duplication (`user`, `user:`, `password`, `password:`, `userEnv`, `userEnv:`, `passwordEnv`, `passwordEnv:`). We could resolve this code smell by factoring out a `SCIAuthenticableLoadSpec` or `SCIAbstractLoadSpecWithCredentials` as a common superclass for all implementing classes.

  @fniephaus How do you think about this, would this refactoring be worth a new class?

### CODE REVIEW

**Comment by fniephaus** [comment]
Does this mean you'd like to support both, `username` *and* `usernameEnv` (same for `password`)? I suggest we force people to use the environment approach in smalltalkCI, otherwise we will see some users putting credentials into their configs.

**Comment by LinqLover** [comment]
`username:` and `password:` already existed before, I was afraid of dropping support for them completely. There could also be harmless usage scenarios such as `squeak/squeak` for public SqueakSource repositories. Does smalltalkCI already have any warning mechanism we could use here?

**Comment by LinqLover** [comment]
Unfortunately, the CI is red because some Pharo jobs raise a `ModificationForbidden` in `SCIMonticelloLoadSpecTest >> testAddLoadedClassesFrom`. This should be fixed in another PR?

**Comment by LinqLover** [comment]
> Unfortunately, the CI is red because some Pharo jobs raise a `ModificationForbidden` in `SCIMonticelloLoadSpecTest >> testAddLoadedClassesFrom`. This should be fixed in another PR?
> 
> EDIT: GitHub says all checks passed, but I keep getting "build failed" emails by Travis, and there indeed some red jobs in the [build](https://travis-ci.com/github/LinqLover/smalltalkCI/builds/199146862). So do I have to care about this? 🤔

While still not related to this PR, these issues should be fixed via https://github.com/pharo-project/pharo/pull/7815. :-)

**Comment by fniephaus** [comment]
Since this still has some open todos, I'm guessing this is not ready for review?
If you could use [PR drafts](https://github.blog/2019-02-14-introducing-draft-pull-requests/), that'd be great. You can even convert this PR into a draft (see "Still in progress? Convert to draft" link on the top right).

**Comment by LinqLover** [comment]
All open todos are related to the questions I noted above. It depends on your opinion only whether additional work is required until this PR can be merged. I was not sure whether this PR state should be called "WIP". :-)

**Comment by fniephaus** [comment]
+1 for `SCIAbstractLoadSpecWithCredentials`, not sure this needs to be tested with an accepted test..up to you :)

**Comment by LinqLover** [comment]
What's up here? Did we hit some limitations?

image
image
image

**Comment by LinqLover** [comment]
@fniephaus It took a bit longer than expected, but now I have factored out `SCIAbstractLoadSpecWithCredentials` and this PR is finally ready for review! :-) Looking at the ancestry of this branch, it might be better to squash this when merging.

**Comment by LinqLover** [comment]
@fniephaus Merge conflicts are resolved and we have a green bar! Let's merge this before it becomes out of sync again! :-)

**Comment by fniephaus** [comment]
Looks like this PR has become part of #485 and was therefore merged already, correct @LinqLover?

**Comment by LinqLover** [comment]
Yes, the changes are already on the master. The idea was to merge this PR first, but no problem. :-) Do we have to close this or can we preserve the statistics by merging it again?

**Comment by fniephaus** [comment]
Sorry, but the order of the two PRs was not clear to me.

If you refer to the diff, then there's no point in merging this one anymore:
image

**Comment by LinqLover** [comment]
Yeah, my only argument for merging this anyway would have been that it looks nicer in the statistics - a closed PR looks like "rejected". But everything is fine, the changes are live and there are no further merge conflicts. 🎉

**Pull request closed without merging**
