### PR TITLE
Fix for #306

### PR DESCRIPTION
**Pull request by fniephaus**

### CODE REVIEW

**Comment by fniephaus** [comment]
@theseion why do you always use `[ci skip]` in your commit messages?

**Comment by gcotelli** [comment]
The Moose builds are failing due to INRIA infrastructure. There was a problem with the Jenkins setup.

**Comment by theseion** [comment]
Because you say so in the readme. But maybe you were only referring to PR's?

**Comment by fniephaus** [comment]
Oh, that comment is only relevant when adding a project to the `README.md`. No need to spin up all builds just because the `README.md` is changed.
`[ci skip]` is good if you can guarantee that the commit does not change smalltalkCI's logic/behavior.

**Comment by theseion** [comment]
Makes sense :)

**Pull request merged**
