### PR TITLE
Use platform aware class in tests

### LINKED ISSUE #618: `PackageOrganizer>>#listAtCategoryNamed:` deprecated in Pharo 12
The smalltalkCI tests [have started to fail on Pharo 12](https://github.com/hpi-swa/smalltalkCI/actions/runs/6990959110/job/19020997366) due to a deprecation:

```
Deprecation: The method PackageOrganizer>>#categories called from SmalltalkCI class>>#allCategoryNames has been deprecated. The manipulation of categories got deprecated in Pharo 12. It is better to manipulate directly the packages and tags.
PackageOrganizer(Object)>>deprecated:
PackageOrganizer>>categories
SmalltalkCI class>>allCategoryNames
SmalltalkCI class>>classesForCategories:
SmalltalkCITest>>testClassesForCategories
SmalltalkCITest(TestCase)>>performTest
```

@theseion Could you (or someone else from the Pharo team) please take a look and fix this?

### PR DESCRIPTION
**Pull request by theseion**
Fixes #618

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks for the PR, Max. I had already adjusted the tests via https://github.com/hpi-swa/smalltalkCI/commit/3f277b9f730c0d38f3be3aebd9ecd1957232659e, but cherry-pick the relevant bits from this PR via https://github.com/hpi-swa/smalltalkCI/commit/e03bd965a8561714b5bbb4e4a23dc826f1a77cf5.

Nonetheless, the Pharo 12 builds still fail:
```
#########################
# 9 tests did not pass: #
#########################

SCIPharoMonticelloLoadSpecTest
 ✗ #testAddLoadedClassesFrom (4ms)
TestFailure: Denial failed
SCIPharoMonticelloLoadSpecTest(TestAsserter)>>assert:description:resumable:
SCIPharoMonticelloLoadSpecTest(TestAsserter)>>deny:description:resumable:
SCIPharoMonticelloLoadSpecTest(TestAsserter)>>deny:description:
SCIPharoMonticelloLoadSpecTest(TestAsserter)>>deny:
SCIPharoMonticelloLoadSpecTest>>testAddLoadedClassesFrom ...deny: (self spec loadedClasses isEmpty)
SCIPharoMonticelloLoadSpecTest(TestCase)>>performTest

SmalltalkCISpecTest
 ✗ #testClassesToTest (9ms)
TestFailure: Assertion failed
SmalltalkCISpecTest(TestAsserter)>>assert:description:resumable:
SmalltalkCISpecTest(TestAsserter)>>assert:description:
SmalltalkCISpecTest(Object)>>assert:
SmalltalkCISpecTest>>testClassesToTest ...assert: (classes includes: SmalltalkCITest)
SmalltalkCISpecTest(TestCase)>>performTest

SmalltalkCITest
 ✗ #testClassesForCategories (6ms)
TestFailure: Assertion failed
SmalltalkCITest(TestAsserter)>>assert:description:resumable:
SmalltalkCITest(TestAsserter)>>assert:description:
SmalltalkCITest(Object)>>assert:
SmalltalkCITest>>testClassesForCategories ...assert: (classes includes: SmalltalkCI)
SmalltalkCITest(TestCase)>>performTest
 ✗ #testClassesFrom (6ms)
TestFailure: Assertion failed
SmalltalkCITest(TestAsserter)>>assert:description:resumable:
SmalltalkCITest(TestAsserter)>>assert:description:
SmalltalkCITest(Object)>>assert:
SmalltalkCITest>>testClassesFrom ...assert: (classes includes: SmalltalkCI)
SmalltalkCITest(TestCase)>>performTest
 ✗ #testClassesInCategory (0ms)
TestFailure: Assertion failed
SmalltalkCITest(TestAsserter)>>assert:description:resumable:
SmalltalkCITest(TestAsserter)>>assert:description:
SmalltalkCITest(Object)>>assert:
SmalltalkCITest>>testClassesInCategory ...assert: (classes includes: SmalltalkCI)
SmalltalkCITest(TestCase)>>performTest
 ✗ #testClassesWithCategoryNames (2ms)
TestFailure: Assertion failed
SmalltalkCITest(TestAsserter)>>assert:description:resumable:
SmalltalkCITest(TestAsserter)>>assert:description:
SmalltalkCITest(Object)>>assert:
SmalltalkCITest>>testClassesWithCategoryNames ...assert: (classes includes: SmalltalkCI)
SmalltalkCITest(TestCase)>>performTest

SCITestReporterXMLTest
 ✗ #testReportSuccess (22ms)
TestFailure: Assertion failed
SCITestReporterXMLTest(TestAsserter)>>assert:description:resumable:
SCITestReporterXMLTest(TestAsserter)>>assert:description:
SCITestReporterXMLTest(Object)>>assert:
SCITestReporterXMLTest>>testReportSuccess ...assert: index > 0
SCITestReporterXMLTest(TestCase)>>performTest

SCITestRunnerTest
 ✗ #testRunClasses (11ms)
TestFailure: Assertion failed
SCITestRunnerTest(TestAsserter)>>assert:description:resumable:
SCITestRunnerTest(TestAsserter)>>assert:description:
SCITestRunnerTest(Object)>>assert:
SCITestRunnerTest>>testRunClasses ...assert: runner isSuccessful
SCITestRunnerTest(TestCase)>>performTest
 ✗ #testRunSpecNamed (12ms)
TestFailure: Assertion failed
SCITestRunnerTest(TestAsserter)>>assert:description:resumable:
SCITestRunnerTest(TestAsserter)>>assert:description:
SCITestRunnerTest(Object)>>assert:
SCITestRunnerTest>>testRunSpecNamed ...assert: runner isSuccessful
SCITestRunnerTest(TestCase)>>performTest
```

https://github.com/hpi-swa/smalltalkCI/actions/runs/7159267912/job/19492329016?pr=619#step:4:996

**Comment by theseion** [comment]
That's because those images are not the `alpha` images. The URL for the Pharo 12 images ends in `120`. We should probably remove `Pharo64-12` from the list of images, or at least from the test matrix. That image hasn't been updated in a while.

**Comment by fniephaus** [comment]
> We should probably remove Pharo64-12 from the list of images, or at least from the test matrix.

I'm not sure I understand. Is Pharo 12 considered stable or not? Nonetheless, the tests are failing in a weird way in that image. Are you sure the code you recently added to find classes in categories is doing what it should be?

**Comment by theseion** [comment]
No, Pharo 12 isn't stable yet. Alpha and 12 are the same thing, but there is already a `120` image, which isn't updated by the nightly build. That means that `Pharo64-12` is not the same thing as `Pharo64-alpha`.

Yes, the code should be fine. It works for the alpha build.

**Pull request closed without merging**
