### PR TITLE
Fix vm download URL as for issue #319

### PR DESCRIPTION
**Pull request by guillep**
Pharo stable and 6.1 should use vm61.

Pharo 6.0, and moose should keep vm60.

### CODE REVIEW

**Comment by fniephaus** [comment]
Do you know if `Moose-6.1` is based on `Pharo-6.1` and also needs a 6.1 vm?

**Comment by guillep** [comment]
No idea, I don't maintain Moose, that's why I did not dare to change it :)

**Comment by fniephaus** [comment]
>Do you know if Moose-6.1 is based on Pharo-6.1 and also needs a 6.1 vm?

@SergeStinckwich can you answer that question?

**Comment by SergeStinckwich** [comment]
Apparently Moose6.1 is based on Pharo 6.1 (update 60510).

**Comment by fniephaus** [comment]
FYI: the Pharo download servers are very slow at the moment (it took almost 5min to download image and vm in [this build](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/284135590)).

**Comment by guillep** [comment]
About the slowness of servers, this is a known issue. @demarey is going to talk with the people from the hosting service to find a solution early next week.

**Comment by fniephaus** [comment]
@guillep ok cool, just wanted to make sure you are aware of this as it can cause CI builds to fail.

**Comment by marianopeck** [comment]
Hi @fniephaus 
After you have merged this PR (which I see you did) do you know how long it takes to have SmalltalkCI runner (the production runner for Travis) to take effect of this fix?

**Comment by fniephaus** [comment]
@marianopeck Travis CI pulls smalltalkCI's `master` branch, so as soon as this was merged it should take effect. Restart your old builds or it should be fixed with your next push.

**Comment by marianopeck** [comment]
thanks @fniephaus  
Yeah, I can confirm it is fixed now! Cool and thanks

**Pull request merged**
