### PR TITLE
Fix #360

### LINKED ISSUE #360: Should update Pharo Stdout access
There was some renaming in the classes providing access to stdio in latest dev Pharo 7. The  platform code should be fixed accordingly.

### PR DESCRIPTION
**Pull request by guillep**
Rename ZnCrPortableWriteStream into ZnNewLineWriterStream

### CODE REVIEW

**Comment by fniephaus** [comment]
Does this need to be backwards compatible?

**Comment by guillep** [comment]
Nope, this is for Pharo-alpha. The class that was renamed does not exist in Pharo<7. It was introduced in Pharo7 and now renamed.

**Comment by fniephaus** [comment]
Ok, thanks!

**Comment by fniephaus** [comment]
The change should now be live. Thanks again for the fix!

**Comment by guillep** [comment]
Thank you!

**Pull request merged**
