### PR TITLE
repository need to include "/" so you can specify local files as "." …

### PR DESCRIPTION
**Pull request by estebanlm**
…or "name" (otherwise you need to add "/." and "/name" which is incorrect.

### CODE REVIEW

**Comment by fniephaus** [comment]
What's the problem with the current definition?
Doesn't `/.` work as intended? You just want to get rid of the very first slash?

**Comment by fniephaus** [comment]
Maybe the README.md is misleading here again and might only need another update?
I just want it to be as consistent as possible across all dialects and I decided to use the slash to make clear its the user's repositories root, if you know what I mean.

**Comment by estebanlm** [comment]
yes, but the slash is non-consistent with the rest of the world, IMO. 
the (IMO, correct) assumption is relative, not absolute... also "root of the project" means in general "from here to down, and slash means "from root of the disk to down"... 
Not that I cannot live with a clarification in the README, but I think this is not correct in general. 

btw... I have a couple of questions related to caching, etc... where should I send them? :P

**Comment by marceltaeumel** [comment]
Yes, using "/something" for a local path is strange. That slash should be part of the outer scope.

**Comment by fniephaus** [comment]
I will update this later today. Thanks for the feedback.
@estebanlm feel free to send your questions to code@fniephaus.com :smiley:

**Pull request merged**
