### PR TITLE
Pharo-alpha should also use the latest VM, not just the latest image

### PR DESCRIPTION
**Pull request by peteruhnak**
Apparently this was also requested in https://github.com/hpi-swa/smalltalkCI/issues/274 (274 however also requests 64bit and threaded heartbeat, which this PR doesn't address)

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks! Will merge as soon as everything is green :)

**Comment by fniephaus** [comment]
Looks like you forgot to update the bash test 😄, I'll take care of that...

**Comment by peteruhnak** [comment]
updated, I didn't realize there was a test for this :)

btw looking at the failing test (https://travis-ci.org/hpi-swa/smalltalkCI/jobs/225184723) it seems odd that a assertion failure would also be considered "unknown failure"

```
ASSERT:expected:<get.pharo.org/vm60> but was:<get.pharo.org/vmLatest60>
ASSERT:Unknown failure encountered running a test
```

**Comment by peteruhnak** [comment]
Practical question: is there some delay before this is usable on Travis? (e.g. does Travis need to update it themselves or something?)

**Comment by fniephaus** [comment]
>btw looking at the failing test (https://travis-ci.org/hpi-swa/smalltalkCI/jobs/225184723) it seems odd that a assertion failure would also be considered "unknown failure"

I'm afraid [shunit2](https://github.com/hpi-swa/smalltalkCI/blob/a73734752eb33dc083296331fc552b529b7a3a52/lib/shunit2) does give better explanations. It's bash after all...

> Practical question: is there some delay before this is usable on Travis? (e.g. does Travis need to update it themselves or something?)

Nope, everything should work as soon as I've merged this :)

**Comment by peteruhnak** [comment]
Appveyor is complaining, but looking at older PRs it seems unrelated and already broken. (e.g. this was just readme change https://ci.appveyor.com/project/smalltalkCI/smalltalkci/build/277 )

**Comment by fniephaus** [comment]
`Pharo-alpha` is listed as allowed failure on AppVeyor. Some recent changes in Pharo's trunk must have broken something in smalltalkCI. Will open an issue, so that I don't forget...

**Comment by peteruhnak** [comment]
Thanks!

**Pull request merged**
