### PR TITLE
Supporting parametrized tests that produce a custom suite.

### PR DESCRIPTION
**Pull request by tesonep**
Pharo allows the subclasses of TestCase to generate a TestSuite with the tests in the TestCase. 
This allows us to create a parametrized test, one test configured with many options spawning different tests. 

Changing the building of the test suite to use #suite and then flattening this suites into the one used by SmalltalkCI.

### CODE REVIEW

**Comment by fniephaus** [comment]
@estebanlm could you have a quick look at this?

**Comment by estebanlm** [comment]
yes, seems ok

**Comment by fniephaus** [comment]
Thanks to both of you, I should have time to merge this tomorrow!

**Comment by fniephaus** [comment]
Thanks for the contribution, @tesonep!

**Pull request merged**
