### PR TITLE
Fix coverage ignore support for pharo

### LINKED ISSUE #441: Fix for #437 breaks coverage ignore support for Pharo
The changes implemented in #437 makes the coverage ignore support not working on Pharo.
In Pharo at least since 6.1 and up versions ` compiledMethod hasLiteral: #ignoreForCoverage --> false` while `compiledMethod refersToLiteral: #ignoreForCoverage --> true`

### PR DESCRIPTION
**Pull request by gcotelli**
Fix #441 Use #refersToLiteral: method in Pharo to discover methods including the <ignoreForCoverage> pragma

### CODE REVIEW

**Comment by gcotelli** [comment]
Some GemStone builds are failing but I cannot figure it out why, because I only touched Pharo related code

**Comment by dalehenrich** [comment]
@gcotelli Here's the [error message for the GemStone build failure](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/592666334#L910):
> Cloning into 'hpi-swa/smalltalkCI'...
> 
> warning: Could not find remote branch 441-Fix-for-437-breaks-coverage-ignore-support-for-Pharo to clone.
> 
> fatal: Remote branch 441-Fix-for-437-breaks-coverage-ignore-support-for-Pharo not found in upstream origin
> 
> The command "eval git clone --depth=50 --branch=441-Fix-for-437-breaks-coverage-ignore-support-for-Pharo https://github.com/hpi-swa/smalltalkCI.git hpi-swa/smalltalkCI " failed. Retrying, 2 of 3.

It's claiming that it can't find the remote branch `441-Fix-for-437-breaks-coverage-ignore-support-for-Pharo`, and I don't see [that branch in the hpi checkout](https://github.com/hpi-swa/smalltalkCI/branches/all)... The branch [is present in your clone](https://github.com/gcotelli/smalltalkCI/tree/441-Fix-for-437-breaks-coverage-ignore-support-for-Pharo), so I'm not sure why the clone itself is failing, but  it seems to be something internal to smalltalkCI and not necessarily related to GemStone ...

**Comment by dalehenrich** [comment]
If you are referring to [this GemStone build](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/592667549#L2248-L2253), then it is failing because [the download of the Pharo vm is failing](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/592667549#L2248-L2253) ... sometimes the pharo site drops download connections --- and retrying the build is the solution ... Or perhaps, something else has changed with the Pharo vm in the last 6 days (master build cleanly 6 days ago)

**Comment by gcotelli** [comment]
The failing test is in the Pharo 3.0 client inside the GemStone job, but I think this never worked because the DNU is in the common superclass  `SCICodeCoverage` , the thing is that now I've introduced a test that checks that behavior :( . 
@fniephaus what can we do here?

Relevant log lines:
```
Testing project...
##################################################
# travisClient_Pharo3.0                          #
# 56 Tests with 0 Failures and 1 Errors in 0.15s #
##################################################
passing_tests_bd82
(55 tests passed)
#########################
# 1 tests did not pass: #
#########################

SCIPharoCodeCoverageTest b84efa_bd82

 ✗ #testIsExcluded (9ms)

MessageNotUnderstood: CompiledMethod>>compiledMethod
CompiledMethod(Object)>>doesNotUnderstand: #compiledMethod
SCIPharoCodeCoverage class(SCICodeCoverage class)>>isExcluded:
SCIPharoCodeCoverage class>>isExcluded:
SCIPharoCodeCoverageTest>>testIsExcluded ...isExcluded: self class >> #methodToIgnoreInCoverage
SCICoverageWrapper>>run:with:in:
SCIPharoCodeCoverageTest(Object)>>perform:
SCIPharoCodeCoverageTest(TestCase)>>performTest
```

**Comment by fniephaus** [comment]
I guess we could a) ignore the error/test case on Pharo 3.0 or b) make it work somehow. I'm leaving that up to you :)

**Comment by dalehenrich** [comment]
Presumably the SCIPharoCodeCoverage class shouldn't be loaded for Pharo3.0? GemStone does not do test coverage and apparently Pharo3.0 does not do test coverage either? 

The Pharo Client tests being triggered in this GemStone build are not intentionally requesting code coverage and I don't expect/desire test coverage to be included in the tests being triggered by GemStone ... so perhaps the controls for whether or not test coverage is enabled is not quite right, yet...

**Comment by fniephaus** [comment]
Right, maybe a baseline update is all it takes to make things work. Could you give that a try please, @gcotelli?

**Comment by gcotelli** [comment]
I will try to update the baseline and exclude the coverage packages for
Pharo 3

**Comment by gcotelli** [comment]
@fniephaus I think I fixed all the problems (the Mac tests are still running but the Linux ones all passed). Please take a look again at the code changes.

**Comment by fniephaus** [comment]
Thanks, @gcotelli! LGTM! Will merge everything after cleaning up redundant metadata changes again.

**Comment by gcotelli** [comment]
Be careful because I moved some classes to a new package... Not all the
metadata changes are superfluos, and I removed the ones I think were just
changes in the order of the methods

**Comment by fniephaus** [comment]
Merged, thanks again @gcotelli!

**Pull request merged**
