### PR TITLE
Fuel pharo9 fixes

### PR DESCRIPTION
**Pull request by theseion**
Fixes one deprecation warning and the use of FuelOutStackDebugAction.

### CODE REVIEW

**Comment by theseion** [comment]
Note that the change is not yet in Pharo 9 but shouldn't be far off. See https://github.com/pharo-project/pharo/issues/9282

**Comment by fniephaus** [comment]
Thanks, @theseion! Looks like you deleted [`repository/SmalltalkCI-Pharo-Core.package/monticello.meta/version` and GemStone doesn't like that.](https://github.com/hpi-swa/smalltalkCI/pull/522/checks?check_run_id=2594965106#step:4:1177)

**Comment by theseion** [comment]
Argh! Thank. I'll fix that.

**Review by fniephaus — APPROVED** [review]
LGTM, thanks!

**Comment by theseion** [comment]
Thanks for the fixes. I mess up with Pharo vs. Filetree every time 🙄 .

**Comment by fniephaus** [comment]
No worries! I wish we could nuke all metadata files... but unfortunately, this would break compatibility with older versions of Squeak and Pharo :(

**Pull request merged**
