### PR TITLE
Fix SmallTalkCi does not work in Pharo9

### LINKED ISSUE #491: SmallTalkCi does not work in Pharo9
SmalltalkCIPharo78 used a deprecated version of FileStream in Pharo.
However, the FileStream class has been removed in Pharo9.

So, I believe that SmallTalkCi should be updated to work with the last version of Pharo.

The problem is in `SmalltalkCIPharo class>>#forceNewFileNamed: aFile do: aBlock`

Maybe we should replace the method by:

```smalltalk
forceNewFileNamed: aFile do: aBlock
	aFile asFileReference writeStreamDo: [ :aStream | aBlock value: aStream ] 
```

### PR DESCRIPTION
**Pull request by badetitou**
This is a try to fix #491

I made this PR to run the project CI (since in my computer some tests are yellow for no reason (maybe windows?))

### CODE REVIEW

**Comment by badetitou** [comment]
It looks like there is another error in P9

**Comment by badetitou** [comment]
The class `SystemReporter` has been removed in P9, but I don't know if it has been replaced and by what.
I'm looking for it

**Comment by fniephaus** [comment]
I'm not up-to-date what's going on in Pharo 9, but `SystemReporter` was removed and added back again recently: https://github.com/hpi-swa/smalltalkCI/pull/484

**Comment by fniephaus** [comment]
Yes, looks like `SmalltalkCIPharo9` is needed. You can always run the tests locally if you want to try out your changes before triggering smalltalkCI's CI pipelines.

**Comment by badetitou** [comment]
Yes, sorry for sending probably thousand of mail from GitHub...

**Comment by badetitou** [comment]
@fniephaus I think the CI cannot run because it uses the branch master of smalltalkCI

**Comment by badetitou** [comment]
Else, in my computer I only have a bug in Stdout export. I try to fix this locally

**Comment by fniephaus** [comment]
Sorry, I have a deadline coming up on Sunday. Will be able to help some time next week.

**Comment by badetitou** [comment]
No problem!

**Comment by badetitou** [comment]
I have testes the PR in my branch of Moose (https://github.com/badetitou/Moose/runs/1555353513)
It appears the bug is fixed 

The build reports bugs that are skipped tests... I don't know why the tests are well skipped in P8, but not in P9

**Comment by badetitou** [comment]
Argg.. In Pharo9, the exception `TestSkip` has been renamed `TestSkipped`

**Comment by fniephaus** [comment]
> Argg.. In Pharo9, the exception TestSkip has been renamed TestSkipped

That's exactly why smalltalkCI relies on contributions like this from the Pharo community. Thanks for looking into this!

**Comment by badetitou** [comment]
I have proposed a fix for Pharo9 by adding a new runner with the new exception and it works in my Moose builde.
The design of my solution can be improved!
But, at least it works for now https://github.com/badetitou/Moose/runs/1555635426?check_suite_focus=true

**Comment by fniephaus** [comment]
Subclass `SCIPharoTestRunner` for Pharo 9 is the right way to address this. Great it's working now! Is this PR now ready to be reviewed?

**Comment by badetitou** [comment]
Yep, ready for review!
Thanks for your time 😄

**Comment by fniephaus** [comment]
@badetitou I've cleaned up this PR and let SmalltalkCIPharo9 inherit from SmalltalkCIPharo78. Could you have a quick look and confirm that you are ok with this?

**Review by fniephaus — APPROVED** [review]
LGTM, thanks a lot!

**Comment by badetitou** [comment]
I have rerun the Ci on my Moose fork without error 👍 
So, it is ok for me

**Comment by fniephaus** [comment]
Ha, I thought your 🚀 is already the confirmation. Your changes are live now!

**Pull request merged**
