### PR TITLE
Add Moose 8.0 and Moose 64bit

### PR DESCRIPTION
**Pull request by badetitou**
I tried to add Moose 8.0 and the 64bits version of Moose 7 and 8

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks for your contribution!

**Comment by fniephaus** [comment]
And it's live! :)

**Comment by fniephaus** [comment]
@badetitou can do confirm this is working?

**Comment by badetitou** [comment]
Hello,

I just tried.
It looks like it works but I have the same issue as https://github.com/hpi-swa/smalltalkCI/issues/420

**Pull request merged**
