### PR TITLE
Update Moose8 Stable location

### PR DESCRIPTION
**Pull request by badetitou**
I have updated the Moose8 stable continuous release location

### CODE REVIEW

**Comment by badetitou** [comment]
I do not know why there is a conflict problem with the last Moose64-8
Maybe because the image is build using smalltalkCI? 

Any idea

**Comment by fniephaus** [comment]
It looks like the [new image](https://github.com/moosetechnology/Moose/releases/download/v8.x.x/Moose8-stable.zip) has some version of smalltalkCI pre-loaded. Why's that?

**Comment by badetitou** [comment]
Indeed. The image is built using the smalltalk ci project. (we use smalltalk ci to create the image )
So the project is loaded

**Comment by fniephaus** [comment]
Yes, smalltalkCI needs to replace itself. I will take a look...

**Comment by badetitou** [comment]
Super!

It looks like a great feature to me if we can build image using smalltalkci 
I'll try to give you a hand if I found time beside my manuscript thesis writing

**Comment by fniephaus** [comment]
Merged via https://github.com/hpi-swa/smalltalkCI/commit/69ad6ca1ebe6de4740b074032a3cfc875e96e0a5. Looks like you forgot about Moose64-trunk ;)

**Comment by badetitou** [comment]
Thanks for the update, We are moving to a new version of Moose (Moose9 based on Pharo9), so the trunk will evolve. But we will see this in a future PR. 
Thanks !

**Pull request closed without merging**
