### PR TITLE
Delete unneeded method #imageInfo in P9 causing CI to fail

### PR DESCRIPTION
**Pull request by hernanmd**

### CODE REVIEW

**Comment by theseion** [comment]
Can you elaborate on the issue? Why is this suddenly the case? I had already fixed the issue with `#imageInfo` being obsolete in Pharo 13.

**Comment by hernanmd** [comment]
> Can you elaborate on the issue? Why is this suddenly the case? I had already fixed the issue with `#imageInfo` being obsolete in Pharo 13.

Hi @theseion .
I was trying to fix a new CI failure while building NewTools in P13: https://github.com/pharo-spec/NewTools/actions/runs/10687297620/job/29624580843#step:4:406
(however it was too late and I couldn't finish it)

The history is like this:

...
Pharo 8 => SystemReporter
Pharo 9 => StSystemReporter
Pharo 10 => StSystemReporter
Pharo 11 => StSystemReporter
Pharo 12 => StSystemReporter(obsolete) -> StSystemReporterPresenter
Pharo 13 => StSystemReporterPresenter

**Comment by theseion** [comment]
Oh, ok, an undeclared variable.

**Review by theseion — APPROVED** [review]

**Comment by hernanmd** [comment]
@theseion any particular reason why this PR wasn't merged? 
Please let me know.

**Comment by theseion** [comment]
I'm accustomed to letting the author merge the PR, if they're a project member.

**Comment by hernanmd** [comment]
Thanks!

**Pull request merged**
