### PR TITLE
Don't disable Iceberg

### LINKED ISSUE #365: Loading a project with tonel dependencies don't work
It seems that loading a project whose dependencies are in tonel format don't work:
See discussion here:
http://forum.world.st/SmalltalkCI-loading-tonel-dependencies-td5073542.html

I think it's probably related to disabling Iceberg metacello integration during the load phase. @fniephaus: did you remember the reason why Iceberg metacello integration is disabled in smalltalkCI?

### PR DESCRIPTION
**Pull request by gcotelli**
This changes fixed #365 . 
@fniephaus I've made this PR over the previous one (#364 ) to avoid conflicts in the metadata files.

I've tested it against a fork of the repository having the original problem. See a passing build here:
https://travis-ci.org/gcotelli/earley-parser/builds/366766621

### CODE REVIEW

**Comment by gcotelli** [comment]
@fniephaus don't forget to merge this changes too. Because without this changes having  a dependency on a tonel project won't work.
I've updated the branch to latest master.

**Comment by fniephaus** [comment]
I haven't, I only wanted to wait for the build pipeline to clear. I will review and merge this tonight. Thanks!

**Comment by fniephaus** [comment]
This basically just reverts https://github.com/hpi-swa/smalltalkCI/commit/149933d8c107ae9601c2ed74a7b2d5387dec6af3#diff-d78f6612aa014afde0964c133a1790d7 which relates to https://github.com/hpi-swa/smalltalkCI/issues/306.

Merging this while assuming that Iceberg-related issues have been fixed in the meantime.

@gcotelli Could you please confirm everything (Tonel, Iceberg, ...) is working as intended?

**Comment by gcotelli** [comment]
I will migrate my projects and report here if any problem arises.

**Comment by fniephaus** [comment]
Perfekt, thanks!

**Pull request merged**
