### PR TITLE
Correctly resume MCMergeOrLoadWarning in Pharo

### PR DESCRIPTION
**Pull request by theseion**
* refactored load warning exception handlers
* added handler for MCMergeOrLoadWarning

fixes issue #293

[ci skip]

### CODE REVIEW

**Comment by fniephaus** [comment]
Mh, this broke the GemStone builds ([see here for example](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/252285938)).

**Comment by theseion** [comment]
I used `#at:ifPresent:ifAbsent:` to look up `MCMergeOrLoadWarning`. I'll have to use a more conservative method then. I'll fix it tonight.

**Comment by fniephaus** [comment]
Maybe solve this via inheritance? If this is only needed for Pharo, add a class method to `SmalltalkCI` and override it in `SmalltalkCIPharo`.

**Comment by theseion** [comment]
Sounds sensible.

**Comment by theseion** [comment]
I've pushed the fix for this to dev directly. BTW, I opted to create subclasses of `SCIMetacelloLoadSpec` (as already exist for `SCIMonticelloLoadSpec`) instead of using a class side method.

**Pull request merged**
