### PR TITLE
Fix for Issue #69

### PR DESCRIPTION
**Pull request by dalehenrich**
The new tests that I wrote were mainly aimed at testing the package-related test creation features which are only for GemStone or Pharo ... presumably it may be useful for Squeak to support pacdkage-based specs as well ... if not the gemstone/pharo tests could be split into separate packages that are only loaded for gemstone/pharo ....

### CODE REVIEW

**Comment by fniephaus** [comment]
+1 for platform-specific test packages. That'd make a lot of sense, because we also need to test platform-specific code.
I will merge this in now and we can add more tests in a next step.

Are any of your tests NOPs on Squeak or do they happen to work on Squeak as well?

**Comment by dalehenrich** [comment]
The tests with gemstone and/or pharo in the name are the platform-specific tests and are noops (passes) on Squeak ...

**Comment by fniephaus** [comment]
Ok, so we should move them to platform-specific packages.

**Comment by dalehenrich** [comment]
I can do the work ---- do you want ot open a separate issue?

**Comment by fniephaus** [comment]
Another PR would be enough, I think. Thanks! :)

**Comment by dalehenrich** [comment]
Haha, but I need a reminder somewhere ... i=unless you want to keep asking me when I'm going to do it:)

**Pull request merged**
