### PR TITLE
418-Do-not-load-STON-dependency-in-Pharo-60-and-later

### LINKED ISSUE #418: Do not load STON dependency in Pharo 6.0 and later
Hi, my build is failing due to a timeout while trying to load SmalltalkCI's dependency on STON

```
Project: Ston stable [0.27]
...RETRY->STON-Core-SvenVanCaekenberghe.90
...RETRY->STON-Core-SvenVanCaekenberghe.90ConnectionTimedOut: Cannot connect to 204.246.122.142:80
```

See https://travis-ci.com/ba-st/Superluminal/jobs/192275250

### PR DESCRIPTION
**Pull request by jecisc**
Load STON only in Pharo 3 and 4
Fixes #418

### CODE REVIEW

**Comment by fniephaus** [comment]
Mh. looks like something is not working correctly. The GemStone builds with older Pharo clients are failing (see [here](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/537992690) and [here](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/537992694)).

**Comment by jecisc** [comment]
Oh, apparently the project is metadataless and since Iceberg (the git management tool in Pharo) only manages metadataless projects it deleted the metadata files. I'll see to revert those changes.

**Comment by fniephaus** [comment]
Thanks, @jecisc! I've cleaned up the rest and will merge this as soon as CI passes :)

**Comment by jecisc** [comment]
Next time I will try to find a way to commit with metadatas. I wonder if Iceberg would be able to use FileTree with metadatas easily. I’ll to check one day if I find the times.

**Comment by gcotelli** [comment]
The last time I have to change something in SmalltalCI, I've used the old
Monticello browser to commit. As far as I remember it still uses the
metadata format

**Pull request merged**
