### PR TITLE
Fix for Pharo-3 clients and misc improvements

### LINKED ISSUE #201: The '975 tests passed' line is misleading
See: https://travis-ci.org/dalehenrich/metacello-work/jobs/166565898#L7644.

The `975 tests passed` shows up in bright green and draws the eye, but the line fails to mention how many failures and errors there were ... I know that the summary in blue contains this information but you have to hunt for it ... I know that the errors/failures listed is a clue that the build didn't succeed, but if there are a number of errors I have to hunt for the information ...

Perhaps a fold with errors and a fold with failures that summarizes the results would be better ... and of course the noisy stack trace at the end needs to be eliminated somehow ... when I scroll to the end of the build, I just see the stack trace and I have to scroll back up an unknown amount to see the actual results of the test ... very annoying ... perhaps putting back the python summary script is the way to go at least it gave a good summary...

### PR DESCRIPTION
**Pull request by fniephaus**
This PR contains fixes for #202, #201, #200, and #199.

@dalehenrich please feel free to have a look at the Travis logs when you have some time and open more issues if necessary.

### CODE REVIEW

**Comment by dalehenrich** [comment]
were you planning on adding the expected failed test test for GemStone? Then I'd be able to easily see what the failed test output for GemStone looks like (the fix for #200)

**Comment by fniephaus** [comment]
[Here you go](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/167114402). I already noticed that the banner is not completely red. But this is an easy tweak.

**Comment by dalehenrich** [comment]
@fniephaus well done ... other than the miscoloring it obth the success and failed tests are very clear ... really like using the folds to hide passing tests .. it is practical to scroll down from the top to see the test results rather than jump to end and scroll backwards:)

**Comment by fniephaus** [comment]
Thanks. I'm now looking at the other issues you opened and see if there's something I can do before I let Travis build everything once again (MacOS builds are currently very busy/slow).

**Pull request merged**
