### PR TITLE
Add tonel support

### LINKED ISSUE #326: Clean up support for Tonel in smalltalkCI
(prerequisite for #325)

Tonel should be just another MCRepository, so in principle it shouldn't be too difficult.
However Tonel has to be loaded into the image before we attempt to load the project.
I don't know if it will autodetect, or if we will need to explicitly state a load strategy in the spec. @estebanlm  should know.
I will be looking at Tonel this weekend, so I will (have to) play with SmalltalkCI support too.

### PR DESCRIPTION
**Pull request by gcotelli**
Attemp to fix #326 (at leats until proper tonel support is implemented)

### CODE REVIEW

**Comment by gcotelli** [comment]
I didn't get why the GemStone build failed. I've touched only Pharo incumbent code.

**Comment by gcotelli** [comment]
The build failure seems to be totally unrelated to this changes. 
```
Fetched -> ConfigurationOfGofer-dkh.45 --- http://seaside.gemtalksystems.com/ss/metacello --- http://seaside.gemtalksystems.com/ss/metacello'Errors in script loaded from /Users/travis/build/hpi-swa/smalltalkCI/_builds/GsDevKit_home/sys/default/pharo/gsDevKitCommandLineLoad.st'
FileWriteError: File /Users/travis/build/hpi-swa/smalltalkCI/_builds/GsDevKit_home/shared/pharo/gsDevKitTmp.changes write failed
```
@fniephaus maybe you can restart the job that failed in travis ? I don't have permissions.

**Comment by gcotelli** [comment]
Now this job worked but timed-out another one that previously worked :(
```
Network availability confirmed.
127.0.0.1	localhost
::1	 ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.14	travis-job-hpi-swa-smalltalkci-361828058.travisci.net travis-job-hpi-swa-smalltalkci-361828058
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by fniephaus** [comment]
Thanks for the PR, I'll take care of the rest. :)
Looks like Travis had some network connectivity issues today. I should get this merged tomorrow!

**Pull request merged**
