### PR TITLE
Add SCIMonticelloLoadSpec and SCIGoferLoadSpec

### PR DESCRIPTION
**Pull request by fniephaus**
This adds support for loading projects with Monticello and Gofer (#152).
Currently, it is only possible to load from a `MCHttpRepository`, but we should be able to support other MCRepositories (e.g. `MCFileTreeRepository`) in the future.

Please let me know what you think about this, @Uko.

Maybe @dalehenrich wants to have a look at this as well.

### CODE REVIEW

**Comment by dalehenrich** [comment]
I'm curious how load order will be preserved if you mix #packages and #versions ... if gofer loads all of the packages at once I suppose it won't matter ... don't recall what the standard behavior of gofer is ... otherwise looks cool ...

**Comment by fniephaus** [comment]
Currently, if you mix `#packages` and `#versions`, it would load all versions first and then the packages. I'm not sure if this is a problem, but I'm also not sure if mixing both is a good idea in the first place.
We either could merge the list into one (e.g. `#packagesAndVersions`) to preserve the order, or one could define more than one `SCIMonticelloLoadSpec` or `SCIGoferLoadSpec` (to avoid confusion, we could disable to mix `#packages` and `#versions`, but I'm again not sure if this would be better).

**Comment by Uko** [comment]
I think that this makes sense. We have to see how people are going to use this to make improvements in the future

**Comment by fniephaus** [comment]
Ok cool, just wanted to make sure that this is what you were looking for...

**Comment by dalehenrich** [comment]
Well package load order is a thing, so mixing packages and versions would break the ability to control load order ... there are other ways to skin the load order cat, so this isn't a deal breaker.... and as @Uko mentions it's worth waiting to see how the usage evolves ...

**Pull request merged**
