### PR TITLE
Add Moose-9.0

### PR DESCRIPTION
**Pull request by badetitou**
This PR aims to add the support of Moose-9.0 (the version under dev)

### CODE REVIEW

**Comment by fniephaus** [comment]
You've missed this list of supported images in the main `run.sh`:
https://github.com/hpi-swa/smalltalkCI/blob/29e49a5893c63f23ad960fa698599523ed142743/run.sh#L213-L214

**Comment by badetitou** [comment]
Indeed, I have added Moose64-9.0 to the list

**Comment by fniephaus** [comment]
Is this ready to be merged?

**Review by fniephaus — APPROVED** [review]
LGTM

**Comment by badetitou** [comment]
It is ok for me

**Pull request merged**
