### PR TITLE
fix system reporter for Pharo 9

### PR DESCRIPTION
**Pull request by demarey**
SystemReporter class was just removed from Pharo 9. Let's fix it.

### CODE REVIEW

**Comment by fniephaus** [comment]
I've pushed a commit to restore and fix the metadata. Will merge this when CI passes...

**Review by fniephaus — APPROVED** [review]
LGTM

**Comment by demarey** [comment]
Thanks Fabio. A temporary fix was pushed into Pharo 9.
A more permanent fix will be done into Pharo but.it will have no impact on smalltalk ci.
We should forget this PR for now.

**Comment by fniephaus** [comment]
What's the "more permanent fix"? We ran into a similar issue with `TestCase`...

**Comment by demarey** [comment]
The right fix will be to split the tool in 2 packages: one for the UI, one for the business code.
See https://github.com/pharo-project/pharo/pull/7659

**Comment by fniephaus** [comment]
Excellent, and thanks for the reference!

**Pull request closed without merging**
